# Generated by Django 2.1.7 on 2019-04-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
