# Generated by Django 2.1.7 on 2019-04-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books_app', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='addBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
